### ISSUE TITLE
[FIX] Set Typescript with ESLint

### ISSUE THREAD

**Issue by mrdemogit** [mrdemogit/react-typescript-starter#27]

**Comment by Harkindey** [comment]
Hi @mrdemogit can you add more description to this issue to see if i can take it up?

**Comment by mrdemogit** [comment]
Hey @Harkindey currently .ts and .tsx files are not validated by eslint 
```
"lint-staged": {
    "*.{js,jsx}": [
      "eslint --no-ignore --fix",
      "prettier --write",
      "git add --force"
    ], .....
```

If you change regex to ` "*.{ts,tsx}":` there are many errors and useless rules for integration linter with typescript..

**Comment by mrdemogit** [comment]
Integrated in 0.3.2
